-- Règles pédagogiques mémorisées explicitement par l’enseignant.
-- Elles sont séparées du cahier et ne sont accessibles qu’à leur propriétaire.

create table if not exists public.assistant_preferences (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  rule text not null check (
    char_length(rule) between 3 and 500
    and rule = btrim(rule)
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists assistant_preferences_owner_rule_idx
on public.assistant_preferences (owner_id, lower(rule));

alter table public.assistant_preferences enable row level security;

drop policy if exists "owner_select_assistant_preferences" on public.assistant_preferences;
create policy "owner_select_assistant_preferences"
on public.assistant_preferences for select to authenticated
using ((select auth.uid()) = owner_id);

drop policy if exists "owner_insert_assistant_preferences" on public.assistant_preferences;
create policy "owner_insert_assistant_preferences"
on public.assistant_preferences for insert to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "owner_delete_assistant_preferences" on public.assistant_preferences;
create policy "owner_delete_assistant_preferences"
on public.assistant_preferences for delete to authenticated
using ((select auth.uid()) = owner_id);

revoke all on table public.assistant_preferences from anon;
grant select, insert, delete on table public.assistant_preferences to authenticated;
grant all on table public.assistant_preferences to service_role;

grant usage, select on sequence public.assistant_preferences_id_seq to authenticated;
grant all on sequence public.assistant_preferences_id_seq to service_role;
