-- Catalogue Google Drive en lecture seule côté utilisateur.
-- Les jetons OAuth chiffrés ne sont jamais accessibles au navigateur.

create table if not exists public.drive_connections (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  refresh_token_ciphertext text not null,
  google_email text,
  scopes text[] not null default '{}',
  change_page_token text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.drive_connections enable row level security;
revoke all on table public.drive_connections from anon, authenticated;
grant all on table public.drive_connections to service_role;

create table if not exists public.drive_connection_status (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  connected boolean not null default false,
  google_email text,
  last_synced_at timestamptz,
  last_error text,
  indexed_file_count integer not null default 0 check (indexed_file_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.drive_connection_status enable row level security;
drop policy if exists "owner_select_drive_status" on public.drive_connection_status;
create policy "owner_select_drive_status"
on public.drive_connection_status for select to authenticated
using ((select auth.uid()) = owner_id);
revoke all on table public.drive_connection_status from anon;
grant select on table public.drive_connection_status to authenticated;
grant all on table public.drive_connection_status to service_role;

create table if not exists public.drive_files (
  owner_id uuid not null references auth.users(id) on delete cascade,
  file_id text not null,
  title text not null,
  mime_type text not null,
  web_view_link text not null,
  modified_time timestamptz,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  md5_checksum text,
  parent_ids text[] not null default '{}',
  path text[] not null default '{}',
  subject text,
  notion text,
  sequence text,
  role text not null default 'other' check (role in (
    'sequence', 'teacher_sheet', 'student_sheet', 'slideshow', 'lesson',
    'exercise', 'assessment', 'correction', 'other'
  )),
  content_excerpt text not null default '' check (length(content_excerpt) <= 50000),
  indexed_at timestamptz not null default now(),
  primary key (owner_id, file_id)
);

alter table public.drive_files enable row level security;
drop policy if exists "owner_select_drive_files" on public.drive_files;
create policy "owner_select_drive_files"
on public.drive_files for select to authenticated
using ((select auth.uid()) = owner_id);
revoke all on table public.drive_files from anon;
grant select on table public.drive_files to authenticated;
grant all on table public.drive_files to service_role;

create index if not exists drive_files_owner_role_idx on public.drive_files (owner_id, role);
create index if not exists drive_files_owner_modified_idx on public.drive_files (owner_id, modified_time desc);

create table if not exists public.drive_sync_runs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('full', 'incremental')),
  status text not null check (status in ('running', 'success', 'error')),
  indexed_file_count integer not null default 0 check (indexed_file_count >= 0),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error_message text
);

alter table public.drive_sync_runs enable row level security;
drop policy if exists "owner_select_drive_sync_runs" on public.drive_sync_runs;
create policy "owner_select_drive_sync_runs"
on public.drive_sync_runs for select to authenticated
using ((select auth.uid()) = owner_id);
revoke all on table public.drive_sync_runs from anon;
grant select on table public.drive_sync_runs to authenticated;
grant all on table public.drive_sync_runs to service_role;
